version: "3.5"

secrets:
  nextcloud_exporter_url:
    name: ${stack_name:-technocore}_nextcloud_exporter_url
    external: true
  nextcloud_exporter_username:
    name: ${stack_name:-technocore}_nextcloud_exporter_username
    external: true
  nextcloud_exporter_password:
    name: ${stack_name:-technocore}_nextcloud_exporter_password
    external: true

services:
  cadvisor:
    command: -logtostderr -docker_only
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      restart_policy:
        condition: any
    image: google/cadvisor:v0.33.0
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - prometheus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  # TODO: Add back SNMP exporter.
  #snmp_exporter:
  #  deploy:
  #    mode: global
  #    restart_policy:
  #      condition: any
  #    resources:
  #      limits:
  #        memory: 128M
  #      reservations:
  #        memory: 64M
  #  image: ricardbejarano/snmp_exporter:0.19.0
  #  logging:
  #    driver: "${LOGGING_DRIVER}"
  #    options:
  #      tag: "{{.Name}}"
  #  networks:
  #    - prometheus

  # TODO: Split nextcloud_exporter into it's own option + .yml file?
  #nextcloud_exporter:
  #  deploy:
  #    mode: global
  #    resources:
  #      limits:
  #        memory: 128M
  #      reservations:
  #        memory: 64M
  #    restart_policy:
  #      condition: any
  #  image: ${image_provider:-scififarms}/technocore-nextcloud-exporter:${TAG:-latest}
  #  logging:
  #    driver: "${LOGGING_DRIVER}"
  #    options:
  #      tag: "{{.Name}}"
  #  networks:
  #    - prometheus
  #  secrets:
  #    - source: nextcloud_exporter_url
  #      target: url
  #    - source: nextcloud_exporter_username
  #      target: username
  #    - source: nextcloud_exporter_password
  #      target: password
  
  node_exporter:
    command:       
      - '--path.procfs=/host/proc'       
      - '--path.sysfs=/host/sys'       
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'       
      # Experimental
      #- '--collector.textfile.directory=/etc/node-exporter/'
      #- '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      #- '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      restart_policy:
        condition: any
    environment:
      - NODE_ID={{.Node.ID}}
    image: prom/node-exporter:v1.0.1
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - prometheus
    # pid: isn't supported in swarm (yet?)
    # pid: "host"
    volumes:       
      - /proc:/host/proc:ro       
      - /sys:/host/sys:ro       
      - /:/host:ro,rslave
