global:       
  # TODO: Make this 1 minute for production.
  scrape_interval:     1m # Set the scrape interval to every 15 seconds. Default is every 1 minute.       
  evaluation_interval: 1m # Evaluate rules every 15 seconds. The default is every 1 minute.                       
  # scrape_timeout is set to the global default (10s).       
  # Attach these labels to any time series or alerts when communicating with       
  # external systems (federation, remote storage, Alertmanager).       
  external_labels:       
      monitor: 'technocore-monitor'       
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.       
#rule_files:       
#  - "first.rules"       
#  - "second.rules"       
scrape_configs:       
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
        labels:                           
          job: 'prometheus'

  - job_name: 'node-exporter'       
    static_configs:       
      - targets: ['node_exporter:9100']       
        labels:                           
          job: 'node-exporter'
                
  - job_name: 'cadvisor'       
    static_configs:                       
      - targets: ['cadvisor:8080']
        labels:                           
          job: 'cadvisor'
  
  - job_name: 'nextcloud'
    static_configs:
      - targets: ['nextcloud_exporter:9205']
        labels:                           
          job: 'nextcloud'

  - job_name: 'vernemq'
    static_configs:
      - targets: ['mqtt:8888']
        labels:                           
          job: 'vernemq'

  - job_name: 'snmp'
    static_configs:
      - targets:
        - 192.168.1.1  # SNMP device.
        labels:                           
          job: 'snmp'
    metrics_path: /snmp
    params:
      module: [ddwrt]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116  # The SNMP exporter's real hostname:po.
    metric_relabel_configs:
      - source_labels: ['__name__']
        target_label: '__name__'
        regex: '(.*)'
        replacement: 'snmp_${1}'

  #- job_name: 'home-assistant'
  #  metrics_path: /api/prometheus
  #  static_configs:
  #    - targets: ['home_assistant:8123']

