global:       
  # TODO: Make this 1 minute for production.
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.       
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.                       
  # scrape_timeout is set to the global default (10s).       
  # Attach these labels to any time series or alerts when communicating with       
  # external systems (federation, remote storage, Alertmanager).       
  external_labels:       
      monitor: 'technocore-monitor'       
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.       
#rule_files:       
#  - "first.rules"       
#  - "second.rules"       
scrape_configs:       
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'       
    static_configs:       
      - targets: ['node_exporter:9100']       
                
  - job_name: 'cadvisor'       
    static_configs:                       
      - targets: ['cadvisor:8080']
  
  - job_name: 'nextcloud'
    static_configs:
      - targets: ['nextcloud_exporter:9205']

  - job_name: 'vernemq'
    static_configs:
      - targets: ['mqtt.local:8888']

  #- job_name: 'home-assistant'
  #  metrics_path: /api/prometheus
  #  static_configs:
  #    - targets: ['home_assistant:8123']

